import re

files = [
    "frontend/app/forecast/page.jsx",
    "frontend/app/insights/page.jsx",
    "frontend/app/agent/page.jsx",
    "frontend/app/components/ForecastClient.jsx",
    "frontend/app/components/AgentClient.jsx",
    "frontend/app/preview/page.jsx",
    "frontend/app/report/page.jsx",
    "frontend/app/upload/page.jsx",
    "frontend/app/page.jsx",
]

translations = {
    "截图 OCR 时序Forecast": "Screenshot OCR Time-Series Forecast",
    "CSV/Excel 时序Forecast": "CSV/Excel Time-Series Forecast",
    "识别Target列": "Detected Target Col",
    "测试期Forecast": "Test Set Forecast",
    "真实Forecast": "Real Forecast",
    "模型Forecast": "Model Forecast",
    "生成Forecast": "Generate Forecast",
    "最佳Forecast": "Best Forecast",
    "点Forecast": "Point Forecast",
    "平均Forecast": "Average Forecast",
    "FutureForecast": "Future Forecast",
    "Future期": "Future Period",
    "Daily (D)期": "Date",
    "Weekly (W)期": "Weekly Period",
    "Weekly (W)转": "Turnover",
    "Quarterly (Q)节性": "Seasonality",
    "Report分析": "Report Analysis",
    "Target是": "Target is",
    "Target列": "Target Column",
    "Detected Time Col": "Detected Time Col",
    "Refine OCR with AI": "Refine OCR with AI",
    "Frequency": "Frequency",
    "Test Set Ratio": "Test Set Ratio",
    "Mode": "Mode",
    "模型比較": "Model Comparison",
    "管理報告": "Management Report",
    "洞察": "Insights",
    "建議": "Suggestions",
    "風險提示": "Risk Warnings",
    "為什麼選這個模型": "Why choose this model",
    "請先到 Upload 頁面上傳資料並生成一次預測，這裡會自動顯示洞察與建議": "Please upload data and generate forecast in the Upload page first, insights and suggestions will appear here.",
    "先確認洞察是否符合你對資料的認知（趨勢、Seasonality、波動）。": "First confirm if insights match your understanding of the data (Trend, Seasonality, Volatility).",
    "再看建議：是否要調整補貨/人力/產能或促銷節奏。": "Then review suggestions: whether to adjust replenishment/staffing/capacity or promotional rhythm.",
    "需要重新跑模型時，回到 Upload 頁面再生成一次即可。": "If you need to rerun the model, just go back to the Upload page and generate again.",
    "（預設：最佳模型）": "(Default: Best Model)",
    "查看模型參數與指標": "View Model Parameters and Metrics",
    "尚未產生報告": "Report not generated yet",
    "执行摘要": "Executive Summary",
    "（用于核对与合规）": "(For verification and compliance)",
    "数据概览（质量与Mode）": "Data Overview (Quality and Mode)",
    "数据主题说明": "Data Theme Description",
    "峰值与低谷（用于规划边界）": "Peaks and Troughs (For Planning Boundaries)",
    "不确定性与风险提示（管理层用）": "Uncertainty & Risk Warnings (For Management)",
    "两项可执行建议（量化）": "Two Actionable Suggestions (Quantified)",
    "模型对比表（按误差排序并突出推荐模型）": "Model Comparison Table (Sorted by Error, Best Highlighted)",
    "排名较低模型原因（摘要）": "Reasons for Lower-ranked Models (Summary)",
    "数据泄露与过拟合检查": "Data Leakage & Overfitting Checks",
    "（用于预算/产能基线）": "(For Budget/Capacity Baselines)",
    "（用于预算/产能基线": "(For Budget/Capacity Baselines",
    "点Forecast是“最可能”的单点；95% 区间给出更现实的波动范围。": "Point forecast is the 'most likely' single point; 95% interval gives a realistic range of volatility.",
    "做资源/库存上限规划优先看上限；保守压缩成本看下限。": "Prioritize upper bound for resource/inventory ceiling planning; prioritize lower bound for conservative cost cutting.",
    "区间越宽，说明不确定性越高，需要更保守的策略。": "Wider interval indicates higher uncertainty, requiring a more conservative strategy.",
    "若 MAPE &gt; 30%，请将Forecast结果视为“高不确定性”，建议增加安全边际或缩短滚动ForecastWeekly (W)期。": "If MAPE > 30%, consider the forecast 'highly uncertain'. Suggest increasing safety margin or shortening rolling forecast period.",
    "若数据量过短或缺失严重，建议补采数据再复核": "If data is too short or severely missing, suggest supplementing data and reviewing.",
    "数据太短（&lt;24）时：Seasonality模型可能不可靠": "When data is too short (<24), seasonal models may be unreliable.",
    "对所有模型使用一致的训练/测试划分（分割Date：": "Consistent train/test split for all models (Split Date: ",
    "测试集观测数据不参与训练与调参；仅用于评估与展示。": "Test set observations are not used for training/tuning; only for evaluation and display.",
    "打印版默认展示前 36 行；完整明细请点击右上角“下载 JSON”。": "Print version shows top 36 rows by default; for full details, click 'Download JSON' in top right.",
    "如何读 95% Forecast区间": "How to Read 95% Forecast Interval",
    "指标公式与划分信息": "Metric Formulas & Split Info",
    "图表 1：回测对比（前 80% 训练 / 后 20% 测试，测试期Forecast用于对比，不使用Future期做误差评估）": "Chart 1: Backtesting Comparison (First 80% Train / Last 20% Test, Test Set Forecast used for comparison, Future period not used for error eval)",
    "图表 2：最佳模型（历史 + 最佳拟合 + 测试期Forecast + Future Forecast）": "Chart 2: Best Model (History + Best Fitted + Test Forecast + Future Forecast)",
    "导出 PDF：点击右上角“下载 PDF”，在浏览器打印对话框选择“另存为 PDF”。": "Export PDF: Click 'Download PDF' in top right, choose 'Save as PDF' in browser print dialog.",
    "一句话解读": "One-Sentence Interpretation",
    "两项最重要建议": "Two Most Important Suggestions",
    "发现主周期：": "Found primary period:",
    "建议差分阶数：": "Suggested differencing order:",
    "无明显周期": "No obvious seasonality",
    "平稳性检验 (ADF)：": "Stationarity (ADF):",
    "自相关性 (Ljung-Box)：": "Autocorrelation (Ljung-Box):",
    "无数据": "No data",
    "时间序列诊断图表": "Time-Series Diagnostics Charts",
    "如果后端未返回诊断图表，此处不显示。": "If the backend does not return diagnostic charts, they will not be displayed here.",
    "未来预测": "Future Forecast",
    "未来": "Future",
    "暂无未来预测数据，请先生成。": "No future forecast data available, please generate first.",
    "各模型未来预测 (Future)": "Future Forecasts by Model",
    "报告未生成或后端未返回数据。": "Report not generated or no data returned from backend.",
    "一、执行摘要": "1. Executive Summary",
    "二、数据与探索性分析 (EDA)": "2. Data & Exploratory Data Analysis (EDA)",
    "平稳性 (ADF)：": "Stationarity (ADF):",
    "自相关性 (Ljung-Box)：": "Autocorrelation (Ljung-Box):",
    "三、模型评估与选择": "3. Model Evaluation & Selection",
    "暂无评估数据": "No evaluation data",
    "四、预测结果与分析": "4. Forecast Results & Analysis",
    "五、业务建议 (由大模型生成)": "5. Business Suggestions (LLM Generated)",
    "上传与参数配置": "Upload & Parameters",
    "上传 CSV/Excel 文件或输入文本、截图，配置参数并生成预测。": "Upload CSV/Excel, enter text, or upload screenshots. Configure parameters and generate forecasts.",
    "支持文本、截图，直接返回分析与预测。": "Supports text and screenshots, returning analysis and forecasts directly.",
    "查看不同模型的拟合效果与评估指标。": "View fitting effects and evaluation metrics of different models.",
    "查看自动生成的结构化分析报告。": "View the auto-generated structured analysis report.",
    "图例：": "Legend:",
    "实际值 (Train)": "Actual (Train)",
    "实际值 (Test)": "Actual (Test)",
    "最佳模型拟合": "Best Model Fitted",
    "最佳模型预测": "Best Model Forecast",
    "悬停查看详细数据": "Hover to view detailed data",
    "最佳模型：": "Best Model:",
    "没有历史或测试集数据": "No historical or test set data",
    "评估指标对比": "Evaluation Metrics Comparison",
    "指标越低越好": "Lower is better",
    "没有评估结果数据。": "No evaluation results available.",
    "各模型预测结果 (Test Set)": "Forecast Results by Model (Test Set)",
    "显示 / 隐藏模型：": "Show / Hide Models:",
    "时间序列成分分析": "Time-Series Components Analysis",
    "历史需求（深蓝": "Historical Demand (Dark Blue",
    "拟合值（橙色虚线": "Fitted Values (Orange Dashed",
    "区间（灰色": "Interval (Gray",
    "值（绿色": "Values (Green",
    "包含 fitted parameters、in-sample 與 hold-out 指標": "Includes fitted parameters, in-sample and hold-out metrics",
    "分割Date：": "Split Date:",
    "前 12 条": "Top 12",
    "实际值 -": "Actual -",
    " / 实际值": " / Actual",
    "用于核对与落地": "For verification and execution",
    "点Forecast": "Point Forecast",
    "不确定性宽度": "Uncertainty Width",
    "峰值（点": "Peak (Point",
    "低谷（点": "Trough (Point",
    "峰值在": "Peak at",
    "低谷在": "Trough at",
    "平均区间宽度约": "Avg interval width is approx",
    "平均Forecast值约": "Avg forecast is approx",
    "相对最近一期变化约": "Change vs last period approx",
    "指标（MA / ETS / ARIMA 为必做": "Metrics (MA / ETS / ARIMA are mandatory",
    "同时给出": "Also providing",
    "in-sample 与 hold-out 的 MAE / RMSE / MAPE": "in-sample and hold-out MAE / RMSE / MAPE",
    "排序指标：": "Sorting Metric:",
    "未生成/未返回的方法：": "Un-generated/un-returned methods:",
    "请先在 Agent 页面生成一次Forecast，然后再打开 Report 页面。": "Please generate a forecast on the Agent page first, then open the Report page.",
    "已整合 Upload/Preview 功能，请使用 Agent 页面。": "Upload/Preview features integrated, please use Agent page.",
    "请确认时间列/Target列后，再次点击": "Please confirm time/Target columns, then click",
    "完成真实Forecast": "to complete the real forecast",
    "模型对比（前 8 行": "Model Comparison (Top 8",
    "回测对比（前 80%": "Backtest Comparison (First 80%",
    "测试期Forecast用于对比": "Test Forecast used for comparison",
    "不使用Future期做误差评估": "Future period not used for error eval",
    "图表（历史": "Chart (History",
    "最佳拟合": "Best Fit",
    "执行中…": "Executing...",
    "可能是后端超时或文件过大": "Possibly backend timeout or file too large",
    "前": "Top",
    "行": "rows",
    "列": "column",
    "数据主题与交付场景": "Data Theme & Scenario",
    "选择文件后点击": "Select file and click",
    "可查看前": "to view top",
    "行并自动": "rows and auto-detect",
    "配置后将启用大模型": "Configuring enables LLM",
    "分析": "analysis",
}

for f in files:
    with open(f, 'r', encoding='utf-8') as file:
        content = file.read()
    
    original = content
    for k, v in translations.items():
        content = content.replace(k, v)
        
    if content != original:
        with open(f, 'w', encoding='utf-8') as file:
            file.write(content)
        print(f"Translated: {f}")

