import os
import re

files = [
    "frontend/app/forecast/page.jsx",
    "frontend/app/insights/page.jsx",
    "frontend/app/agent/page.jsx",
    "frontend/app/components/ForecastClient.jsx",
    "frontend/app/components/AgentClient.jsx",
    "frontend/app/preview/page.jsx",
    "frontend/app/report/page.jsx",
    "frontend/app/upload/page.jsx",
    "frontend/app/page.jsx",
]

translations = {
    # page.jsx headers/subtitles
    "未来预测图表与方法选择。": "Future forecast charts and method selection.",
    "报告": "Report",
    "一个入口支持文本 / CSV / 截图，直接返回预测与报告方案。": "A single entry point for text, CSV, and screenshots, returning forecasts and reports directly.",
    "上传与参数": "Upload & Parameters",
    "选择文件并配置频率、模型等参数。": "Select files and configure frequency, models, etc.",
    "预测": "Forecast",
    "数据预览": "Data Preview",
    "上传后快速检查数据，确认时间列与目标列。": "Quickly check data after uploading to confirm time and target columns.",
    "智能分析与评估。": "Intelligent analysis and evaluation.",
    "自动生成的结构化总结。": "Automatically generated structured summary.",
    "首页": "Home",
    
    # common strings
    "通用预测 Agent": "Universal Forecast Agent",
    "支持文本、CSV/Excel、截图输入。CSV/Excel 会直接生成预测与报告；截图支持 OCR 抽表后做真实拟合预测。": "Supports text, CSV/Excel, and screenshots. CSV/Excel generates forecasts and reports directly; screenshots support OCR extraction followed by actual forecasting.",
    "API 地址": "API Base URL",
    "使用本机后端": "Use Local Backend",
    "后端：": "Backend: ",
    "已连接": "Connected",
    "未连接": "Disconnected",
    "（请在项目根目录终端运行：python3 -m uvicorn backend.main:app --reload --port 8013）": "(Please run in root dir: python3 -m uvicorn backend.main:app --port 8000)",
    "上传文件（可选）": "Upload File (Optional)",
    "数据文件（CSV / Excel）": "Data File (CSV / Excel)",
    "数据预览（CSV/Excel/截图OCR）": "Data Preview (CSV/Excel/Screenshot OCR)",
    "预览前 30 行": "Preview Top 30 Rows",
    "预览数据": "Preview Data",
    "预览中…": "Previewing...",
    "频率": "Frequency",
    "日": "Daily (D)",
    "周": "Weekly (W)",
    "月": "Monthly (M)",
    "季": "Quarterly (Q)",
    "年": "Yearly (Y)",
    "测试集比例": "Test Set Ratio",
    "随机种子": "Random Seed",
    "预测期数": "Forecast Periods",
    "预测期数（periods）": "Forecast Periods",
    "时间列名（可选）": "Time Column (Optional)",
    "例如：date / 日期": "e.g. date",
    "例如：日期 / date": "e.g. date",
    "目标列名（可选）": "Target Column (Optional)",
    "例如：demand / 销量": "e.g. demand",
    "例如：销量 / demand": "e.g. demand",
    "高级模型（可选）": "Advanced Models (Optional)",
    "模型范围": "Model Scope",
    "启用高级模型": "Enable Advanced Models",
    "数据集名称（可选）": "Dataset Name (Optional)",
    "例如：2026Q2_零食销售_华东": "e.g. 2026Q2_Sales_East",
    "主题/场景（可选）": "Theme/Scenario (Optional)",
    "主题/场景": "Theme/Scenario",
    "如 retail_inventory": "e.g. retail_inventory",
    "LLM 开关": "LLM Switch",
    "启用 DeepSeek": "Enable DeepSeek",
    "DeepSeek API Key（必填）": "DeepSeek API Key (Required)",
    "DeepSeek API Key（可选）": "DeepSeek API Key (Optional)",
    "配置后将启用大模型报告分析": "Enables LLM report analysis when configured",
    "OCR 修复（截图）": "OCR Refine (Screenshot)",
    "用 AI 修复 OCR": "Refine OCR with AI",
    "业务描述/问题（可选）": "Business Description/Prompt (Optional)",
    "例如：这是某零食每日销量和售价数据，请帮我预测未来两周销量并给库存建议；或描述截图中的图表并给出预测方案。": "e.g., Forecast sales for the next two weeks and provide inventory suggestions based on the data.",
    "补充说明（可选）": "Additional Notes (Optional)",
    "补充业务目标、约束、交付要求。": "Supplementary business goals, constraints, delivery requirements.",
    "数据主题与交付场景（用于报告撰写）": "Data Theme & Delivery Scenario (For Report Generation)",
    "未选择": "Unselected",
    "零售库存/补货": "Retail Inventory / Replenishment",
    "销售运营": "Sales Operations",
    "人员排班": "Workforce Scheduling",
    "环境/湿度/温度控制": "Facility Climate Control",
    "营销投放": "Marketing Campaigns",
    "其他": "Other",
    "数据描述（可选）": "Data Description (Optional)",
    "例如：该数据为某零食在华东地区的每日销售金额与销量；目标是降低缺货并控制库存周转。": "e.g., Daily sales data for a snack in the East region; goal is to reduce stockouts and control inventory turnover.",
    "该信息会写入结构化 report 的封面与执行摘要，用于生成更贴近交付场景的建议与表述。": "This info will be included in the report cover and executive summary to provide more contextual advice.",
    "可选高级模型（勾选后会出现在 Forecast 图表中）": "Optional Advanced Models (Will appear in Forecast charts when checked)",
    "提示：Forecast 页面只能切换显示；要“生成并返回”某个高级模型曲线，需要在这里勾选后重新生成一次。": "Tip: You can only toggle visibility on the Forecast page. To generate curves for an advanced model, check it here and regenerate.",
    "生成预测": "Generate Forecast",
    "运行中…": "Running...",
    "请求失败": "Request Failed",
    "请求失败（可能是后端超时或文件过大）": "Request failed (possibly backend timeout or file too large)",
    "请先选择CSV或Excel文件": "Please select a CSV or Excel file first",
    "预览失败（后端无响应或文件错误）": "Preview failed (backend unresponsive or file error)",
    "选择文件后点击“预览数据”，可查看前 30 行并自动识别时间列/目标列。": "Select a file and click 'Preview Data' to see top 30 rows and auto-detect time/target columns.",
    "选择文件后点击“预览数据”。": "Select a file and click 'Preview Data'.",
    "去生成预测": "Go to Generate Forecast",
    "生成预测需要在 Upload 页面设置频率、测试集比例、模型等参数。": "Generating forecasts requires setting frequency, test ratio, and models on the Upload page.",
    "识别列：时间": "Detected: Time",
    "目标": "Target",
    "请先选择 CSV/Excel 或截图文件": "Please select a CSV/Excel or screenshot file first",
    "预览仅支持 CSV/Excel/图片（PNG/JPG/WEBP/GIF/BMP/TIFF）": "Preview only supports CSV/Excel/Images (PNG/JPG/WEBP/GIF/BMP/TIFF)",
    "预览结果（前 30 行）": "Preview Results (Top 30 Rows)",
    "预览（前 30 行）": "Preview (Top 30 Rows)",
    "AI 修复 OCR 失败：DeepSeek 余额不足（已回退为原始 OCR 结果）。": "AI OCR refine failed: LLM insufficient balance (fell back to raw OCR).",
    "AI 修复 OCR 失败（已回退为原始 OCR 结果）：": "AI OCR refine failed (fell back to raw OCR): ",
    "已使用 AI 修复 OCR。": "OCR refined with AI. ",
    "提示：": "Tip: ",
    "请至少输入一段文本，或上传CSV/Excel/截图。": "Please enter some text, or upload a CSV/Excel/screenshot.",
    "运行 Agent": "Run Agent",
    "已提取截图表格，请确认时间列/目标列后，再次点击“运行 Agent”完成真实预测。": "Extracted table from screenshot. Please confirm time/target columns and click 'Run Agent' again to complete the forecast.",
    "DeepSeek 余额不足（已自动回退到传统模型预测）。": "LLM insufficient balance (auto-fallback to traditional models).",
    "DeepSeek 调用失败（已自动回退到传统模型预测）：": "LLM call failed (auto-fallback to traditional models): ",
    "模式": "Mode",
    "截图 OCR 时序预测": "Screenshot OCR Time-Series Forecast",
    "CSV/Excel 时序预测": "CSV/Excel Time-Series Forecast",
    "识别时间列": "Detected Time Col",
    "识别目标列": "Detected Target Col",
    "多模态理解与建议": "Multi-modal Understanding & Suggestions",
    "输入类型": "Input Type",
    "暂无结果，请先在上方表单提交。": "No results yet, please submit the form above.",
    "切换为图表视图（若适用）": "Switch to Chart View (if applicable)",
    "执行中…": "Executing...",
    "预测结果图表": "Forecast Results Chart",
    "预测数据：": "Forecast Data:",
    "置信区间：": "Confidence Interval:",
    "分析与建议（大模型）：": "Analysis & Suggestions (LLM):",
    "多模态大模型分析报告": "Multi-modal LLM Analysis Report",
    "总结：": "Summary:",
    "可预测指标（Targets）：": "Predictable Targets:",
    "推荐指标：": "Recommended Target:",
    "预测方案：": "Forecast Plan:",
    "报告大纲：": "Report Outline:",
    "需要澄清的问题：": "Questions for Clarification:",
    "暂无图表数据。如果是 OCR 截图模式，请先确认列名并再次运行。": "No chart data available. If in OCR mode, confirm column names and run again.",
    "预测结果（JSON）": "Forecast Results (JSON)",
    "折叠 JSON": "Collapse JSON",
    "展开 JSON": "Expand JSON",
    "全屏": "Fullscreen",
    "报告（Report）": "Report",
    "评估（Insights）": "Evaluation (Insights)",
    "暂无预测图表数据，请先生成。": "No forecast chart data available, please generate first.",
    "图例：": "Legend:",
    "实际值 (Train)": "Actual (Train)",
    "实际值 (Test)": "Actual (Test)",
    "最佳模型拟合": "Best Model Fitted",
    "最佳模型预测": "Best Model Forecast",
    "悬停查看详细数据": "Hover to view detailed data",
    "最佳模型：": "Best Model:",
    "没有历史或测试集数据": "No historical or test set data",
    "评估指标对比": "Evaluation Metrics Comparison",
    "指标越低越好": "Lower is better",
    "没有评估结果数据。": "No evaluation results available.",
    "各模型预测结果 (Test Set)": "Forecast Results by Model (Test Set)",
    "显示 / 隐藏模型：": "Show / Hide Models:",
    "时间序列成分分析": "Time-Series Components Analysis",
    "平稳性检验 (ADF)：": "Stationarity (ADF):",
    "自相关性 (Ljung-Box)：": "Autocorrelation (Ljung-Box):",
    "周期性：": "Seasonality:",
    "发现主周期：": "Found primary period:",
    "建议差分阶数：": "Suggested differencing order:",
    "无明显周期": "No obvious seasonality",
    "无数据": "No data",
    "时间序列诊断图表": "Time-Series Diagnostics Charts",
    "如果后端未返回诊断图表，此处不显示。": "If the backend does not return diagnostic charts, they will not be displayed here.",
    "未来预测": "Future Forecast",
    "未来": "Future",
    "暂无未来预测数据，请先生成。": "No future forecast data available, please generate first.",
    "各模型未来预测 (Future)": "Future Forecasts by Model",
    "报告未生成或后端未返回数据。": "Report not generated or no data returned from backend.",
    "一、执行摘要": "1. Executive Summary",
    "二、数据与探索性分析 (EDA)": "2. Data & Exploratory Data Analysis (EDA)",
    "平稳性 (ADF)：": "Stationarity (ADF):",
    "自相关性 (Ljung-Box)：": "Autocorrelation (Ljung-Box):",
    "三、模型评估与选择": "3. Model Evaluation & Selection",
    "暂无评估数据": "No evaluation data",
    "四、预测结果与分析": "4. Forecast Results & Analysis",
    "五、业务建议 (由大模型生成)": "5. Business Suggestions (LLM Generated)",
    "上传与参数配置": "Upload & Parameters",
    "上传 CSV/Excel 文件或输入文本、截图，配置参数并生成预测。": "Upload CSV/Excel, enter text, or upload screenshots. Configure parameters and generate forecasts.",
    "支持文本、截图，直接返回分析与预测。": "Supports text and screenshots, returning analysis and forecasts directly.",
    "查看不同模型的拟合效果与评估指标。": "View fitting effects and evaluation metrics of different models.",
    "查看自动生成的结构化分析报告。": "View the auto-generated structured analysis report.",
}

def translate_file(filepath):
    if not os.path.exists(filepath):
        return
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for k, v in translations.items():
        content = content.replace(k, v)
        
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Translated: {filepath}")

for f in files:
    translate_file(f)
